=== ZeePal/aws-iam-actions/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/ZeePal/aws-iam-actions",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "name",
    "prefix",
    "url",
    "actions",
    "resourceTypes",
    "conditionKeys"
  ],
  "properties": {
    "name": {
      "description": "The Name of the AWS Service",
      "type": "string",
      "examples": [
        "Identity And Access Management",
        "AWS Security Token Service",
        "Amazon GuardDuty",
        "Amazon S3"
      ]
    },
    "prefix": {
      "description": "The service's prefix for all its actions",
      "type": "string",
      "pattern": "^[a-z0-9-]{2,40}$",
      "examples": [
        "iam",
        "sts",
        "guardduty",
        "s3"
      ]
    },
    "url": {
      "$ref": "#/$defs/documentUrl"
    },
    "actions": {
      "description": "The Actions table lists all the actions that you can use in an IAM policy statement's Action element.",
      "type": "object",
      "additionalProperties": false,
      "patternProperties": {
        "^[A-Za-z0-9]{3,80}$": {
          "description": "An Action.",
          "type": "object",
          "additionalProperties": false,
          "required": [
            "description",
            "accessLevel",
            "permissionOnly",
            "resourceTypes",
            "conditionKeys",
            "dependentActions",
            "url"
          ],
          "properties": {
            "description": {
              "description": "Yo Dawg, Heard you like descriptions. So we put a description in your description.",
              "type": "string",
              "examples": [
                "Grants permission to create a new role",
                "Grants permission to obtain a set of temporary security credentials that you can use to access AWS resources that you might not normally have access to",
                "Grants permission to retrieve GuardDuty findings",
                "Grants permission to create a new bucket"
              ]
            },
            "accessLevel": {
              "description": "https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_understand-policy-summary-access-level-summaries.html",
              "enum": [
                "List",
                "Read",
                "Tagging",
                "Write",
                "Permissions management"
              ]
            },
            "permissionOnly": {
              "description": "Some services include permission-only actions that don't directly correspond to an API operation.",
              "type": "boolean"
            },
            "resourceTypes": {
              "description": "The Resource types column indicates whether the action supports resource-level permissions.",
              "type": "object",
              "additionalProperties": false,
              "patternProperties": {
                "^[A-Za-z0-9-_/ ]{2,80}$": {
                  "type": "object",
                  "description": "A Resource Type.",
                  "additionalProperties": false,
                  "required": [
                    "required",
                    "conditionKeys"
                  ],
                  "properties": {
                    "required": {
                      "description": "Required resources are indicated in the table with an asterisk (*).",
                      "type": [
                        "boolean",
                        "null"
                      ]
                    },
                    "conditionKeys": {
                      "$ref": "#/$defs/listOfConditionKeys"
                    }
                  }
                }
              }
            },
            "conditionKeys": {
              "$ref": "#/$defs/listOfConditionKeys"
            },
            "dependentActions": {
              "description": "The Dependent actions column includes any additional permissions that you must have,",
              "type": "array",
              "uniqueItems": true,
              "items": {
                "description": "A Dependent action.",
                "type": "string",
                "pattern": "^[a-z0-9-]{2,40}:[A-Za-z0-9]{3,50}$",
                "examples": [
                  "iam:PassRole",
                  "s3:GetObject"
                ]
              }
            },
            "url": {
              "$ref": "#/$defs/documentUrl"
            }
          }
        }
      }
    },
    "resourceTypes": {
      "description": "The Resource types table lists all the resource types that you can specify as an ARN in the Resource policy element.",
      "type": "object",
      "additionalProperties": false,
      "patternProperties": {
        "^[A-Za-z0-9-_/ ]{2,80}$": {
          "description": "A Resource type.",
          "type": "object",
          "additionalProperties": false,
          "required": [
            "arn",
            "conditionKeys",
            "url"
          ],
          "properties": {
            "arn": {
              "description": "The ARN column specifies the Amazon Resource Name (ARN) format that you must use to reference resources of this type.",
              "type": "string",
              "pattern": "^arn:[A-Za-z0-9-${}]+:[A-Za-z0-9-${}*]+:[A-Za-z0-9-${}*]*:[A-Za-z0-9-${}*]*:[A-Za-z0-9-${}/:]+",
              "examples": [
                "arn:${Partition}:iam::${Account}:role/${RoleNameWithPath}",
                "arn:${Partition}:guardduty:${Region}:${Account}:detector/${DetectorId}",
                "arn:${Partition}:s3:::${BucketName}/${ObjectName}"
              ]
            },
            "conditionKeys": {
              "$ref": "#/$defs/listOfConditionKeys"
            },
            "url": {
              "$ref": "#/$defs/documentUrl"
            }
          }
        }
      }
    },
    "conditionKeys": {
      "description": "The condition keys table lists all of the condition context keys that you can use in an IAM policy statement's Condition element.",
      "type": "object",
      "additionalProperties": false,
      "patternProperties": {
        "^[a-z0-9-.]{2,40}:[A-Za-z0-9-/${}_.<>:]{2,50}$": {
          "description": "A Condition key.",
          "type": "object",
          "additionalProperties": false,
          "required": [
            "description",
            "type",
            "url"
          ],
          "properties": {
            "description": {
              "description": "Yo Dawg, Heard you like descriptions. So we put a description in your description.",
              "type": "string",
              "examples": [
                "Filters access if the specified policy is set as the permissions boundary on the IAM entity (user or role)",
                "Filters access by the unique identifier required when you assume a role in another account",
                "Filters access by tag key-value pairs attached to the resource",
                "Filters access by canned ACL in the request's x-amz-acl header"
              ]
            },
            "type": {
              "description": "The Type column specifies the data type of the condition key.",
              "enum": [
                "ARN",
                "Bool",
                "Date",
                "Numeric",
                "String",
                "ArrayOfARN",
                "ArrayOfBool",
                "ArrayOfString"
              ]
            },
            "url": {
              "$ref": "#/$defs/documentUrl"
            }
          }
        }
      }
    }
  },
  "$defs": {
    "documentUrl": {
      "description": "The url to the hyperlinked documentation.",
      "type": [
        "string",
        "null"
      ],
      "pattern": "^https://(docs\\.)?aws\\.amazon\\.com/",
      "examples": [
        "https://docs.aws.amazon.com/service-authorization/latest/reference/list_identityandaccessmanagement.html",
        "https://docs.aws.amazon.com/IAM/latest/APIReference/API_CreateRole.html",
        "https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html",
        "https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_iam-condition-keys.html#ck_PassedToService"
      ]
    },
    "listOfConditionKeys": {
      "description": "The Condition keys column includes keys that you can specify in a policy statement's Condition element.",
      "type": "array",
      "uniqueItems": true,
      "items": {
        "description": "A Condition key.",
        "type": "string",
        "pattern": "^[a-z0-9-.]{2,40}:[A-Za-z0-9-/${}_.<>:]{2,50}$",
        "examples": [
          "iam:PermissionsBoundary",
          "sts:ExternalId",
          "aws:ResourceTag/${TagKey}",
          "s3:x-amz-acl"
        ]
      }
    }
  }
}

=== ZeePal/aws-iam-actions/data/awsconnector/aws_connector_service.json
{
  "name": "AWS Connector Service",
  "prefix": "awsconnector",
  "url": "https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsconnectorservice.html",
  "actions": {
    "GetConnectorHealth": {
      "description": "Retrieves all health metrics that were published from the Server Migration Connector.",
      "accessLevel": "Read",
      "permissionOnly": true,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/server-migration-service/latest/userguide/prereqs.html#connector-permissions"
    },
    "RegisterConnector": {
      "description": "Registers AWS Connector with AWS Connector Service.",
      "accessLevel": "Write",
      "permissionOnly": true,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/server-migration-service/latest/userguide/prereqs.html#connector-permissions"
    },
    "ValidateConnectorId": {
      "description": "Validates Server Migration Connector Id that was registered with AWS Connector Service.",
      "accessLevel": "Read",
      "permissionOnly": true,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/server-migration-service/latest/userguide/prereqs.html#connector-permissions"
    }
  },
  "resourceTypes": {},
  "conditionKeys": {}
}

=== ZeePal/aws-iam-actions/data/application-autoscaling/aws_application_auto_scaling.json
{
  "name": "AWS Application Auto Scaling",
  "prefix": "application-autoscaling",
  "url": "https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsapplicationautoscaling.html",
  "actions": {
    "DeleteScalingPolicy": {
      "description": "Grants permission to delete a scaling policy",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/autoscaling/application/APIReference/API_DeleteScalingPolicy.html"
    },
    "DeleteScheduledAction": {
      "description": "Grants permission to delete a scheduled action",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/autoscaling/application/APIReference/API_DeleteScheduledAction.html"
    },
    "DeregisterScalableTarget": {
      "description": "Grants permission to deregister a scalable target",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/autoscaling/application/APIReference/API_DeregisterScalableTarget.html"
    },
    "DescribeScalableTargets": {
      "description": "Grants permission to describe one or more scalable targets in the specified namespace",
      "accessLevel": "Read",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/autoscaling/application/APIReference/API_DescribeScalableTargets.html"
    },
    "DescribeScalingActivities": {
      "description": "Grants permission to describe a set of scaling activities or all scaling activities in the specified namespace",
      "accessLevel": "Read",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/autoscaling/application/APIReference/API_DescribeScalingActivities.html"
    },
    "DescribeScalingPolicies": {
      "description": "Grants permission to describe a set of scaling policies or all scaling policies in the specified namespace",
      "accessLevel": "Read",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/autoscaling/application/APIReference/API_DescribeScalingPolicies.html"
    },
    "DescribeScheduledActions": {
      "description": "Grants permission to describe a set of scheduled actions or all scheduled actions in the specified namespace",
      "accessLevel": "Read",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/autoscaling/application/APIReference/API_DescribeScheduledActions.html"
    },
    "PutScalingPolicy": {
      "description": "Grants permission to create and update a scaling policy for a scalable target",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/autoscaling/application/APIReference/API_PutScalingPolicy.html"
    },
    "PutScheduledAction": {
      "description": "Grants permission to create and update a scheduled action for a scalable target",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/autoscaling/application/APIReference/API_PutScheduledAction.html"
    },
    "RegisterScalableTarget": {
      "description": "Grants permission to register AWS or custom resources as scalable targets with Application Auto Scaling and to update configuration parameters used to manage a scalable target",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/autoscaling/application/APIReference/API_RegisterScalableTarget.html"
    }
  },
  "resourceTypes": {},
  "conditionKeys": {}
}

=== ZeePal/aws-iam-actions/data/sumerian/amazon_sumerian.json
{
  "name": "Amazon Sumerian",
  "prefix": "sumerian",
  "url": "https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonsumerian.html",
  "actions": {
    "Login": {
      "description": "Grants permission to log into the Sumerian console",
      "accessLevel": "Write",
      "permissionOnly": true,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/sumerian/latest/userguide/sumerian-permissions.html"
    },
    "ViewRelease": {
      "description": "Grants permission to view a project release",
      "accessLevel": "Read",
      "permissionOnly": true,
      "resourceTypes": {
        "project": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/sumerian/latest/userguide/sumerian-permissions.html"
    }
  },
  "resourceTypes": {
    "project": {
      "arn": "arn:${Partition}:sumerian:${Region}:${Account}:project:${ProjectName}",
      "conditionKeys": [],
      "url": "https://docs.aws.amazon.com/sumerian/latest/userguide/sumerian-concepts.html"
    }
  },
  "conditionKeys": {}
}

=== ZeePal/aws-iam-actions/data/firehose/amazon_kinesis_firehose.json
{
  "name": "Amazon Kinesis Firehose",
  "prefix": "firehose",
  "url": "https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonkinesisfirehose.html",
  "actions": {
    "CreateDeliveryStream": {
      "description": "Grants permission to create a delivery stream",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {
        "deliverystream": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [
        "aws:RequestTag/${TagKey}",
        "aws:TagKeys"
      ],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/firehose/latest/APIReference/API_CreateDeliveryStream.html"
    },
    "DeleteDeliveryStream": {
      "description": "Grants permission to delete a delivery stream and its data",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {
        "deliverystream": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/firehose/latest/APIReference/API_DeleteDeliveryStream.html"
    },
    "DescribeDeliveryStream": {
      "description": "Grants permission to describe the specified delivery stream and gets the status",
      "accessLevel": "Read",
      "permissionOnly": false,
      "resourceTypes": {
        "deliverystream": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/firehose/latest/APIReference/API_DescribeDeliveryStream.html"
    },
    "ListDeliveryStreams": {
      "description": "Grants permission to list your delivery streams",
      "accessLevel": "List",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/firehose/latest/APIReference/API_ListDeliveryStreams.html"
    },
    "ListTagsForDeliveryStream": {
      "description": "Grants permission to list the tags for the specified delivery stream",
      "accessLevel": "List",
      "permissionOnly": false,
      "resourceTypes": {
        "deliverystream": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/firehose/latest/APIReference/API_ListTagsForDeliveryStream.html"
    },
    "PutRecord": {
      "description": "Grants permission to write a single data record into an Amazon Kinesis Firehose delivery stream",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {
        "deliverystream": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/firehose/latest/APIReference/API_PutRecord.html"
    },
    "PutRecordBatch": {
      "description": "Grants permission to write multiple data records into a delivery stream in a single call, which can achieve higher throughput per producer than when writing single records",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {
        "deliverystream": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/firehose/latest/APIReference/API_PutRecordBatch.html"
    },
    "StartDeliveryStreamEncryption": {
      "description": "Grants permission to enable server-side encryption (SSE) for the delivery stream",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {
        "deliverystream": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/firehose/latest/APIReference/API_StartDeliveryStreamEncryption.html"
    },
    "StopDeliveryStreamEncryption": {
      "description": "Grants permission to disable the specified destination of the specified delivery stream",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {
        "deliverystream": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/firehose/latest/APIReference/API_StopDeliveryStreamEncryption.html"
    },
    "TagDeliveryStream": {
      "description": "Grants permission to add or update tags for the specified delivery stream",
      "accessLevel": "Tagging",
      "permissionOnly": false,
      "resourceTypes": {
        "deliverystream": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [
        "aws:RequestTag/${TagKey}",
        "aws:TagKeys"
      ],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/firehose/latest/APIReference/API_TagDeliveryStream.html"
    },
    "UntagDeliveryStream": {
      "description": "Grants permission to remove tags from the specified delivery stream",
      "accessLevel": "Tagging",
      "permissionOnly": false,
      "resourceTypes": {
        "deliverystream": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [
        "aws:TagKeys"
      ],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/firehose/latest/APIReference/API_UntagDeliveryStream.html"
    },
    "UpdateDestination": {
      "description": "Grants permission to update the specified destination of the specified delivery stream",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {
        "deliverystream": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/firehose/latest/APIReference/API_UpdateDestination.html"
    }
  },
  "resourceTypes": {
    "deliverystream": {
      "arn": "arn:${Partition}:firehose:${Region}:${Account}:deliverystream/${DeliveryStreamName}",
      "conditionKeys": [
        "aws:ResourceTag/${TagKey}"
      ],
      "url": "https://docs.aws.amazon.com/firehose/latest/dev/basic-create.html"
    }
  },
  "conditionKeys": {
    "aws:RequestTag/${TagKey}": {
      "description": "Filters actions based on the tags that are passed in the request",
      "type": "String",
      "url": "https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-requesttag"
    },
    "aws:ResourceTag/${TagKey}": {
      "description": "Filters actions based on the tags associated with the resource",
      "type": "String",
      "url": "https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-resourcetag"
    },
    "aws:TagKeys": {
      "description": "Filters actions based on the tag keys that are passed in the request",
      "type": "ArrayOfString",
      "url": "https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-tagkeys"
    }
  }
}

=== ZeePal/aws-iam-actions/data/savingsplans/aws_savings_plans.json
{
  "name": "AWS Savings Plans",
  "prefix": "savingsplans",
  "url": "https://docs.aws.amazon.com/service-authorization/latest/reference/list_awssavingsplans.html",
  "actions": {
    "CreateSavingsPlan": {
      "description": "Grants permission to create a savings plan",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [
        "aws:RequestTag/${TagKey}",
        "aws:TagKeys"
      ],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/savingsplans/latest/APIReference/API_CreateSavingsPlan.html"
    },
    "DeleteQueuedSavingsPlan": {
      "description": "Grants permission to delete the queued savings plan associated with customers account",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {
        "savingsplan": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [
        "aws:ResourceTag/${TagKey}"
      ],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/savingsplans/latest/APIReference/API_DeleteQueuedSavingsPlan.html"
    },
    "DescribeSavingsPlanRates": {
      "description": "Grants permission to describe the rates associated with customers savings plan",
      "accessLevel": "Read",
      "permissionOnly": false,
      "resourceTypes": {
        "savingsplan": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [
        "aws:ResourceTag/${TagKey}"
      ],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/savingsplans/latest/APIReference/API_DescribeSavingsPlanRates.html"
    },
    "DescribeSavingsPlans": {
      "description": "Grants permission to describe the savings plans associated with customers account",
      "accessLevel": "Read",
      "permissionOnly": false,
      "resourceTypes": {
        "savingsplan": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [
        "aws:ResourceTag/${TagKey}"
      ],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/savingsplans/latest/APIReference/API_DescribeSavingsPlans.html"
    },
    "DescribeSavingsPlansOfferingRates": {
      "description": "Grants permission to describe the rates assciated with savings plans offerings",
      "accessLevel": "Read",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/savingsplans/latest/APIReference/API_DescribeSavingsPlansOfferingRates.html"
    },
    "DescribeSavingsPlansOfferings": {
      "description": "Grants permission to describe the savings plans offerings that customer is eligible to purchase",
      "accessLevel": "Read",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/savingsplans/latest/APIReference/API_DescribeSavingsPlansOfferings.html"
    },
    "ListTagsForResource": {
      "description": "Grants permission to list tags for a savings plan",
      "accessLevel": "List",
      "permissionOnly": false,
      "resourceTypes": {
        "savingsplan": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/savingsplans/latest/APIReference/API_ListTagsForResource.html"
    },
    "TagResource": {
      "description": "Grants permission to tag a savings plan",
      "accessLevel": "Tagging",
      "permissionOnly": false,
      "resourceTypes": {
        "savingsplan": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [
        "aws:RequestTag/${TagKey}",
        "aws:TagKeys"
      ],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/savingsplans/latest/APIReference/API_TagResource.html"
    },
    "UntagResource": {
      "description": "Grants permission to untag a savings plan",
      "accessLevel": "Tagging",
      "permissionOnly": false,
      "resourceTypes": {
        "savingsplan": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [
        "aws:TagKeys"
      ],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/savingsplans/latest/APIReference/API_UntagResource.html"
    }
  },
  "resourceTypes": {
    "savingsplan": {
      "arn": "arn:${Partition}:savingsplans::${Account}:savingsplan/${ResourceId}",
      "conditionKeys": [
        "aws:ResourceTag/${TagKey}"
      ],
      "url": "https://docs.aws.amazon.com/savingsplans/latest/userguide/API_SavingsPlan.html"
    }
  },
  "conditionKeys": {
    "aws:RequestTag/${TagKey}": {
      "description": "Filters actions based on the allowed set of values for each of the tags",
      "type": "String",
      "url": "https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-requesttag"
    },
    "aws:ResourceTag/${TagKey}": {
      "description": "Filters actions based on tag-value assoicated with the resource",
      "type": "String",
      "url": "https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-resourcetag"
    },
    "aws:TagKeys": {
      "description": "Filters actions based on the presence of mandatory tags in the request",
      "type": "String",
      "url": "https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-tagkeys"
    }
  }
}

=== ZeePal/aws-iam-actions/data/rhelkb/amazon_rhel_knowledgebase_portal.json
{
  "name": "Amazon RHEL Knowledgebase Portal",
  "prefix": "rhelkb",
  "url": "https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonrhelknowledgebaseportal.html",
  "actions": {
    "GetRhelURL": {
      "description": "Grants permission to access the Red Hat Knowledgebase portal",
      "accessLevel": "Read",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/systems-manager/latest/userguide/fleet-rhel.html"
    }
  },
  "resourceTypes": {},
  "conditionKeys": {}
}
