=== ZeePal/aws-iam-actions/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/ZeePal/aws-iam-actions",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "name",
    "prefix",
    "url",
    "actions",
    "resourceTypes",
    "conditionKeys"
  ],
  "properties": {
    "name": {
      "description": "The Name of the AWS Service",
      "type": "string",
      "examples": [
        "Identity And Access Management",
        "AWS Security Token Service",
        "Amazon GuardDuty",
        "Amazon S3"
      ]
    },
    "prefix": {
      "description": "The service's prefix for all its actions",
      "type": "string",
      "pattern": "^[a-z0-9-]{2,40}$",
      "examples": [
        "iam",
        "sts",
        "guardduty",
        "s3"
      ]
    },
    "url": {
      "$ref": "#/$defs/documentUrl"
    },
    "actions": {
      "description": "The Actions table lists all the actions that you can use in an IAM policy statement's Action element.",
      "type": "object",
      "additionalProperties": false,
      "patternProperties": {
        "^[A-Za-z0-9]{3,80}$": {
          "description": "An Action.",
          "type": "object",
          "additionalProperties": false,
          "required": [
            "description",
            "accessLevel",
            "permissionOnly",
            "resourceTypes",
            "conditionKeys",
            "dependentActions",
            "url"
          ],
          "properties": {
            "description": {
              "description": "Yo Dawg, Heard you like descriptions. So we put a description in your description.",
              "type": "string",
              "examples": [
                "Grants permission to create a new role",
                "Grants permission to obtain a set of temporary security credentials that you can use to access AWS resources that you might not normally have access to",
                "Grants permission to retrieve GuardDuty findings",
                "Grants permission to create a new bucket"
              ]
            },
            "accessLevel": {
              "description": "https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_understand-policy-summary-access-level-summaries.html",
              "enum": [
                "List",
                "Read",
                "Tagging",
                "Write",
                "Permissions management"
              ]
            },
            "permissionOnly": {
              "description": "Some services include permission-only actions that don't directly correspond to an API operation.",
              "type": "boolean"
            },
            "resourceTypes": {
              "description": "The Resource types column indicates whether the action supports resource-level permissions.",
              "type": "object",
              "additionalProperties": false,
              "patternProperties": {
                "^[A-Za-z0-9-_/ ]{2,80}$": {
                  "type": "object",
                  "description": "A Resource Type.",
                  "additionalProperties": false,
                  "required": [
                    "required",
                    "conditionKeys"
                  ],
                  "properties": {
                    "required": {
                      "description": "Required resources are indicated in the table with an asterisk (*).",
                      "type": [
                        "boolean",
                        "null"
                      ]
                    },
                    "conditionKeys": {
                      "$ref": "#/$defs/listOfConditionKeys"
                    }
                  }
                }
              }
            },
            "conditionKeys": {
              "$ref": "#/$defs/listOfConditionKeys"
            },
            "dependentActions": {
              "description": "The Dependent actions column includes any additional permissions that you must have,",
              "type": "array",
              "uniqueItems": true,
              "items": {
                "description": "A Dependent action.",
                "type": "string",
                "pattern": "^[a-z0-9-]{2,40}:[A-Za-z0-9]{3,50}$",
                "examples": [
                  "iam:PassRole",
                  "s3:GetObject"
                ]
              }
            },
            "url": {
              "$ref": "#/$defs/documentUrl"
            }
          }
        }
      }
    },
    "resourceTypes": {
      "description": "The Resource types table lists all the resource types that you can specify as an ARN in the Resource policy element.",
      "type": "object",
      "additionalProperties": false,
      "patternProperties": {
        "^[A-Za-z0-9-_/ ]{2,80}$": {
          "description": "A Resource type.",
          "type": "object",
          "additionalProperties": false,
          "required": [
            "arn",
            "conditionKeys",
            "url"
          ],
          "properties": {
            "arn": {
              "description": "The ARN column specifies the Amazon Resource Name (ARN) format that you must use to reference resources of this type.",
              "type": "string",
              "pattern": "^arn:[A-Za-z0-9-${}]+:[A-Za-z0-9-${}*]+:[A-Za-z0-9-${}*]*:[A-Za-z0-9-${}*]*:[A-Za-z0-9-${}/:]+",
              "examples": [
                "arn:${Partition}:iam::${Account}:role/${RoleNameWithPath}",
                "arn:${Partition}:guardduty:${Region}:${Account}:detector/${DetectorId}",
                "arn:${Partition}:s3:::${BucketName}/${ObjectName}"
              ]
            },
            "conditionKeys": {
              "$ref": "#/$defs/listOfConditionKeys"
            },
            "url": {
              "$ref": "#/$defs/documentUrl"
            }
          }
        }
      }
    },
    "conditionKeys": {
      "description": "The condition keys table lists all of the condition context keys that you can use in an IAM policy statement's Condition element.",
      "type": "object",
      "additionalProperties": false,
      "patternProperties": {
        "^[a-z0-9-.]{2,40}:[A-Za-z0-9-/${}_.<>:]{2,50}$": {
          "description": "A Condition key.",
          "type": "object",
          "additionalProperties": false,
          "required": [
            "description",
            "type",
            "url"
          ],
          "properties": {
            "description": {
              "description": "Yo Dawg, Heard you like descriptions. So we put a description in your description.",
              "type": "string",
              "examples": [
                "Filters access if the specified policy is set as the permissions boundary on the IAM entity (user or role)",
                "Filters access by the unique identifier required when you assume a role in another account",
                "Filters access by tag key-value pairs attached to the resource",
                "Filters access by canned ACL in the request's x-amz-acl header"
              ]
            },
            "type": {
              "description": "The Type column specifies the data type of the condition key.",
              "enum": [
                "ARN",
                "Bool",
                "Date",
                "Numeric",
                "String",
                "ArrayOfARN",
                "ArrayOfBool",
                "ArrayOfString"
              ]
            },
            "url": {
              "$ref": "#/$defs/documentUrl"
            }
          }
        }
      }
    }
  },
  "$defs": {
    "documentUrl": {
      "description": "The url to the hyperlinked documentation.",
      "type": [
        "string",
        "null"
      ],
      "pattern": "^https://(docs\\.)?aws\\.amazon\\.com/",
      "examples": [
        "https://docs.aws.amazon.com/service-authorization/latest/reference/list_identityandaccessmanagement.html",
        "https://docs.aws.amazon.com/IAM/latest/APIReference/API_CreateRole.html",
        "https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html",
        "https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_iam-condition-keys.html#ck_PassedToService"
      ]
    },
    "listOfConditionKeys": {
      "description": "The Condition keys column includes keys that you can specify in a policy statement's Condition element.",
      "type": "array",
      "uniqueItems": true,
      "items": {
        "description": "A Condition key.",
        "type": "string",
        "pattern": "^[a-z0-9-.]{2,40}:[A-Za-z0-9-/${}_.<>:]{2,50}$",
        "examples": [
          "iam:PermissionsBoundary",
          "sts:ExternalId",
          "aws:ResourceTag/${TagKey}",
          "s3:x-amz-acl"
        ]
      }
    }
  }
}

=== ZeePal/aws-iam-actions/data/opsworks-cm/aws_opsworks_configuration_management.json
{
  "name": "AWS OpsWorks Configuration Management",
  "prefix": "opsworks-cm",
  "url": "https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsopsworksconfigurationmanagement.html",
  "actions": {
    "AssociateNode": {
      "description": "Grants permission to associate a node to a configuration management server",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/opsworks-cm/latest/APIReference/API_AssociateNode.html"
    },
    "CreateBackup": {
      "description": "Grants permission to create a backup for the specified server",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/opsworks-cm/latest/APIReference/API_CreateBackup.html"
    },
    "CreateServer": {
      "description": "Grants permission to create a new server",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/opsworks-cm/latest/APIReference/API_CreateServer.html"
    },
    "DeleteBackup": {
      "description": "Grants permission to delete the specified backup and possibly its S3 bucket",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/opsworks-cm/latest/APIReference/API_DeleteBackup.html"
    },
    "DeleteServer": {
      "description": "Grants permission to delete the specified server with its corresponding CloudFormation stack and possibly the S3 bucket",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/opsworks-cm/latest/APIReference/API_DeleteServer.html"
    },
    "DescribeAccountAttributes": {
      "description": "Grants permission to describe the service limits for the user's account",
      "accessLevel": "List",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/opsworks-cm/latest/APIReference/API_DescribeAccountAttributes.html"
    },
    "DescribeBackups": {
      "description": "Grants permission to describe a single backup, all backups of a specified server or all backups of the user's account",
      "accessLevel": "List",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/opsworks-cm/latest/APIReference/API_DescribeBackups.html"
    },
    "DescribeEvents": {
      "description": "Grants permission to describe all events of the specified server",
      "accessLevel": "List",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/opsworks-cm/latest/APIReference/API_DescribeEvents.html"
    },
    "DescribeNodeAssociationStatus": {
      "description": "Grants permission to describe the association status for the specified node token and the specified server",
      "accessLevel": "List",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/opsworks-cm/latest/APIReference/API_DescribeNodeAssociationStatus.html"
    },
    "DescribeServers": {
      "description": "Grants permission to describe the specified server or all servers of the user's account",
      "accessLevel": "List",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/opsworks-cm/latest/APIReference/API_DescribeServers.html"
    },
    "DisassociateNode": {
      "description": "Grants permission to disassociate a specified node from a server",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/opsworks-cm/latest/APIReference/API_DisassociateNode.html"
    },
    "ExportServerEngineAttribute": {
      "description": "Grants permission to export an engine attribute from a server",
      "accessLevel": "Read",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/opsworks-cm/latest/APIReference/API_ExportServerEngineAttribute.html"
    },
    "ListTagsForResource": {
      "description": "Grants permission to list the tags that are applied to the specified server or backup",
      "accessLevel": "Read",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/opsworks-cm/latest/APIReference/API_ListTagsForResource.html"
    },
    "RestoreServer": {
      "description": "Grants permission to apply a backup to specified server. Possibly swaps out the ec2-instance if specified",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/opsworks-cm/latest/APIReference/API_RestoreServer.html"
    },
    "StartMaintenance": {
      "description": "Grants permission to start the server maintenance immediately",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/opsworks-cm/latest/APIReference/API_StartMaintenance.html"
    },
    "TagResource": {
      "description": "Grants permission to apply tags to the specified server or backup",
      "accessLevel": "Tagging",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/opsworks-cm/latest/APIReference/API_TagResource.html"
    },
    "UntagResource": {
      "description": "Grants permission to remove tags from the specified server or backup",
      "accessLevel": "Tagging",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/opsworks-cm/latest/APIReference/API_UntagResource.html"
    },
    "UpdateServer": {
      "description": "Grants permission to update general server settings",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/opsworks-cm/latest/APIReference/API_UpdateServer.html"
    },
    "UpdateServerEngineAttributes": {
      "description": "Grants permission to update server settings specific to the configuration management type",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/opsworks-cm/latest/APIReference/API_UpdateServerEngineAttributes.html"
    }
  },
  "resourceTypes": {
    "backup": {
      "arn": "arn:${Partition}:opsworks-cm::${Account}:backup/${ServerName}-{Date-and-Time-Stamp-of-Backup}",
      "conditionKeys": [],
      "url": null
    },
    "server": {
      "arn": "arn:${Partition}:opsworks-cm::${Account}:server/${ServerName}/${UniqueId}",
      "conditionKeys": [],
      "url": null
    }
  },
  "conditionKeys": {}
}

=== ZeePal/aws-iam-actions/data/elastictranscoder/amazon_elastic_transcoder.json
{
  "name": "Amazon Elastic Transcoder",
  "prefix": "elastictranscoder",
  "url": "https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonelastictranscoder.html",
  "actions": {
    "CancelJob": {
      "description": "Cancel a job that Elastic Transcoder has not begun to process",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {
        "job": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/elastictranscoder/latest/developerguide/cancel-job.html"
    },
    "CreateJob": {
      "description": "Create a job",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {
        "pipeline": {
          "required": true,
          "conditionKeys": []
        },
        "preset": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/elastictranscoder/latest/developerguide/create-job.html"
    },
    "CreatePipeline": {
      "description": "Create a pipeline",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/elastictranscoder/latest/developerguide/create-pipeline.html"
    },
    "CreatePreset": {
      "description": "Create a preset",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/elastictranscoder/latest/developerguide/create-preset.html"
    },
    "DeletePipeline": {
      "description": "Delete a pipeline",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {
        "pipeline": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/elastictranscoder/latest/developerguide/delete-pipeline.html"
    },
    "DeletePreset": {
      "description": "Delete a preset",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {
        "preset": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/elastictranscoder/latest/developerguide/delete-preset.html"
    },
    "ListJobsByPipeline": {
      "description": "Get a list of the jobs that you assigned to a pipeline",
      "accessLevel": "List",
      "permissionOnly": false,
      "resourceTypes": {
        "pipeline": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/elastictranscoder/latest/developerguide/list-jobs-by-pipeline.html"
    },
    "ListJobsByStatus": {
      "description": "Get information about all of the jobs associated with the current AWS account that have a specified status",
      "accessLevel": "List",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/elastictranscoder/latest/developerguide/list-jobs-by-status.html"
    },
    "ListPipelines": {
      "description": "Get a list of the pipelines associated with the current AWS account",
      "accessLevel": "List",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/elastictranscoder/latest/developerguide/list-pipelines.html"
    },
    "ListPresets": {
      "description": "Get a list of all presets associated with the current AWS account",
      "accessLevel": "List",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/elastictranscoder/latest/developerguide/list-presets.html"
    },
    "ReadJob": {
      "description": "Get detailed information about a job",
      "accessLevel": "Read",
      "permissionOnly": false,
      "resourceTypes": {
        "job": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/elastictranscoder/latest/developerguide/get-job.html"
    },
    "ReadPipeline": {
      "description": "Get detailed information about a pipeline",
      "accessLevel": "Read",
      "permissionOnly": false,
      "resourceTypes": {
        "pipeline": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/elastictranscoder/latest/developerguide/get-pipeline.html"
    },
    "ReadPreset": {
      "description": "Get detailed information about a preset",
      "accessLevel": "Read",
      "permissionOnly": false,
      "resourceTypes": {
        "preset": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/elastictranscoder/latest/developerguide/get-preset.html"
    },
    "TestRole": {
      "description": "Test the settings for a pipeline to ensure that Elastic Transcoder can create and process jobs",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/elastictranscoder/latest/developerguide/test-pipeline-role.html"
    },
    "UpdatePipeline": {
      "description": "Update settings for a pipeline",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {
        "pipeline": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/elastictranscoder/latest/developerguide/update-pipeline.html"
    },
    "UpdatePipelineNotifications": {
      "description": "Update only Amazon Simple Notification Service (Amazon SNS) notifications for a pipeline",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {
        "pipeline": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/elastictranscoder/latest/developerguide/update-pipeline-notifications.html"
    },
    "UpdatePipelineStatus": {
      "description": "Pause or reactivate a pipeline, so the pipeline stops or restarts processing jobs, update the status for the pipeline",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {
        "pipeline": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/elastictranscoder/latest/developerguide/update-pipeline-status.html"
    }
  },
  "resourceTypes": {
    "job": {
      "arn": "arn:${Partition}:elastictranscoder:${Region}:${Account}:job/${JobId}",
      "conditionKeys": [],
      "url": "https://docs.aws.amazon.com/elastictranscoder/latest/developerguide/operations-jobs.html"
    },
    "pipeline": {
      "arn": "arn:${Partition}:elastictranscoder:${Region}:${Account}:pipeline/${PipelineId}",
      "conditionKeys": [],
      "url": "https://docs.aws.amazon.com/elastictranscoder/latest/developerguide/operations-pipelines.html"
    },
    "preset": {
      "arn": "arn:${Partition}:elastictranscoder:${Region}:${Account}:preset/${PresetId}",
      "conditionKeys": [],
      "url": "https://docs.aws.amazon.com/elastictranscoder/latest/developerguide/operations-presets.html"
    }
  },
  "conditionKeys": {}
}

=== ZeePal/aws-iam-actions/data/workmailmessageflow/amazon_workmail_message_flow.json
{
  "name": "Amazon WorkMail Message Flow",
  "prefix": "workmailmessageflow",
  "url": "https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonworkmailmessageflow.html",
  "actions": {
    "GetRawMessageContent": {
      "description": "Grants permission to read the content of email messages with the specified message ID",
      "accessLevel": "Read",
      "permissionOnly": false,
      "resourceTypes": {
        "RawMessage": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/workmail/latest/APIReference/API_messageflow_GetRawMessageContent.html"
    },
    "PutRawMessageContent": {
      "description": "Grants permission to update the content of email messages with the specified message ID",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {
        "RawMessage": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/workmail/latest/APIReference/API_messageflow_PutRawMessageContent.html"
    }
  },
  "resourceTypes": {
    "RawMessage": {
      "arn": "arn:${Partition}:workmailmessageflow:${Region}:${Account}:message/${OrganizationId}/${Context}/${MessageId}",
      "conditionKeys": [],
      "url": "https://docs.aws.amazon.com/workmail/latest/adminguide/lambda-content.html"
    }
  },
  "conditionKeys": {}
}

=== ZeePal/aws-iam-actions/data/wickr/aws_wickr.json
{
  "name": "AWS Wickr",
  "prefix": "wickr",
  "url": "https://docs.aws.amazon.com/service-authorization/latest/reference/list_awswickr.html",
  "actions": {
    "CreateAdminSession": {
      "description": "Grants permission to create and manage Wickr networks",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/wickr/latest/adminguide/security-iam.html"
    },
    "ListNetworks": {
      "description": "Grants permission to view Wickr networks",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/wickr/latest/adminguide/security-iam.html"
    }
  },
  "resourceTypes": {},
  "conditionKeys": {}
}
