=== ZeePal/aws-iam-actions/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/ZeePal/aws-iam-actions",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "name",
    "prefix",
    "url",
    "actions",
    "resourceTypes",
    "conditionKeys"
  ],
  "properties": {
    "name": {
      "description": "The Name of the AWS Service",
      "type": "string",
      "examples": [
        "Identity And Access Management",
        "AWS Security Token Service",
        "Amazon GuardDuty",
        "Amazon S3"
      ]
    },
    "prefix": {
      "description": "The service's prefix for all its actions",
      "type": "string",
      "pattern": "^[a-z0-9-]{2,40}$",
      "examples": [
        "iam",
        "sts",
        "guardduty",
        "s3"
      ]
    },
    "url": {
      "$ref": "#/$defs/documentUrl"
    },
    "actions": {
      "description": "The Actions table lists all the actions that you can use in an IAM policy statement's Action element.",
      "type": "object",
      "additionalProperties": false,
      "patternProperties": {
        "^[A-Za-z0-9]{3,80}$": {
          "description": "An Action.",
          "type": "object",
          "additionalProperties": false,
          "required": [
            "description",
            "accessLevel",
            "permissionOnly",
            "resourceTypes",
            "conditionKeys",
            "dependentActions",
            "url"
          ],
          "properties": {
            "description": {
              "description": "Yo Dawg, Heard you like descriptions. So we put a description in your description.",
              "type": "string",
              "examples": [
                "Grants permission to create a new role",
                "Grants permission to obtain a set of temporary security credentials that you can use to access AWS resources that you might not normally have access to",
                "Grants permission to retrieve GuardDuty findings",
                "Grants permission to create a new bucket"
              ]
            },
            "accessLevel": {
              "description": "https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_understand-policy-summary-access-level-summaries.html",
              "enum": [
                "List",
                "Read",
                "Tagging",
                "Write",
                "Permissions management"
              ]
            },
            "permissionOnly": {
              "description": "Some services include permission-only actions that don't directly correspond to an API operation.",
              "type": "boolean"
            },
            "resourceTypes": {
              "description": "The Resource types column indicates whether the action supports resource-level permissions.",
              "type": "object",
              "additionalProperties": false,
              "patternProperties": {
                "^[A-Za-z0-9-_/ ]{2,80}$": {
                  "type": "object",
                  "description": "A Resource Type.",
                  "additionalProperties": false,
                  "required": [
                    "required",
                    "conditionKeys"
                  ],
                  "properties": {
                    "required": {
                      "description": "Required resources are indicated in the table with an asterisk (*).",
                      "type": [
                        "boolean",
                        "null"
                      ]
                    },
                    "conditionKeys": {
                      "$ref": "#/$defs/listOfConditionKeys"
                    }
                  }
                }
              }
            },
            "conditionKeys": {
              "$ref": "#/$defs/listOfConditionKeys"
            },
            "dependentActions": {
              "description": "The Dependent actions column includes any additional permissions that you must have,",
              "type": "array",
              "uniqueItems": true,
              "items": {
                "description": "A Dependent action.",
                "type": "string",
                "pattern": "^[a-z0-9-]{2,40}:[A-Za-z0-9]{3,50}$",
                "examples": [
                  "iam:PassRole",
                  "s3:GetObject"
                ]
              }
            },
            "url": {
              "$ref": "#/$defs/documentUrl"
            }
          }
        }
      }
    },
    "resourceTypes": {
      "description": "The Resource types table lists all the resource types that you can specify as an ARN in the Resource policy element.",
      "type": "object",
      "additionalProperties": false,
      "patternProperties": {
        "^[A-Za-z0-9-_/ ]{2,80}$": {
          "description": "A Resource type.",
          "type": "object",
          "additionalProperties": false,
          "required": [
            "arn",
            "conditionKeys",
            "url"
          ],
          "properties": {
            "arn": {
              "description": "The ARN column specifies the Amazon Resource Name (ARN) format that you must use to reference resources of this type.",
              "type": "string",
              "pattern": "^arn:[A-Za-z0-9-${}]+:[A-Za-z0-9-${}*]+:[A-Za-z0-9-${}*]*:[A-Za-z0-9-${}*]*:[A-Za-z0-9-${}/:]+",
              "examples": [
                "arn:${Partition}:iam::${Account}:role/${RoleNameWithPath}",
                "arn:${Partition}:guardduty:${Region}:${Account}:detector/${DetectorId}",
                "arn:${Partition}:s3:::${BucketName}/${ObjectName}"
              ]
            },
            "conditionKeys": {
              "$ref": "#/$defs/listOfConditionKeys"
            },
            "url": {
              "$ref": "#/$defs/documentUrl"
            }
          }
        }
      }
    },
    "conditionKeys": {
      "description": "The condition keys table lists all of the condition context keys that you can use in an IAM policy statement's Condition element.",
      "type": "object",
      "additionalProperties": false,
      "patternProperties": {
        "^[a-z0-9-.]{2,40}:[A-Za-z0-9-/${}_.<>:]{2,50}$": {
          "description": "A Condition key.",
          "type": "object",
          "additionalProperties": false,
          "required": [
            "description",
            "type",
            "url"
          ],
          "properties": {
            "description": {
              "description": "Yo Dawg, Heard you like descriptions. So we put a description in your description.",
              "type": "string",
              "examples": [
                "Filters access if the specified policy is set as the permissions boundary on the IAM entity (user or role)",
                "Filters access by the unique identifier required when you assume a role in another account",
                "Filters access by tag key-value pairs attached to the resource",
                "Filters access by canned ACL in the request's x-amz-acl header"
              ]
            },
            "type": {
              "description": "The Type column specifies the data type of the condition key.",
              "enum": [
                "ARN",
                "Bool",
                "Date",
                "Numeric",
                "String",
                "ArrayOfARN",
                "ArrayOfBool",
                "ArrayOfString"
              ]
            },
            "url": {
              "$ref": "#/$defs/documentUrl"
            }
          }
        }
      }
    }
  },
  "$defs": {
    "documentUrl": {
      "description": "The url to the hyperlinked documentation.",
      "type": [
        "string",
        "null"
      ],
      "pattern": "^https://(docs\\.)?aws\\.amazon\\.com/",
      "examples": [
        "https://docs.aws.amazon.com/service-authorization/latest/reference/list_identityandaccessmanagement.html",
        "https://docs.aws.amazon.com/IAM/latest/APIReference/API_CreateRole.html",
        "https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html",
        "https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_iam-condition-keys.html#ck_PassedToService"
      ]
    },
    "listOfConditionKeys": {
      "description": "The Condition keys column includes keys that you can specify in a policy statement's Condition element.",
      "type": "array",
      "uniqueItems": true,
      "items": {
        "description": "A Condition key.",
        "type": "string",
        "pattern": "^[a-z0-9-.]{2,40}:[A-Za-z0-9-/${}_.<>:]{2,50}$",
        "examples": [
          "iam:PermissionsBoundary",
          "sts:ExternalId",
          "aws:ResourceTag/${TagKey}",
          "s3:x-amz-acl"
        ]
      }
    }
  }
}

=== ZeePal/aws-iam-actions/data/aws-marketplace/aws_marketplace_metering_service.json
{
  "name": "AWS Marketplace Metering Service",
  "prefix": "aws-marketplace",
  "url": "https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsmarketplacemeteringservice.html",
  "actions": {
    "BatchMeterUsage": {
      "description": "Grants permission to post metering records for a set of customers for SaaS applications",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/marketplacemetering/latest/APIReference/API_BatchMeterUsage.html"
    },
    "MeterUsage": {
      "description": "Grants permission to emit metering records",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/marketplacemetering/latest/APIReference/API_MeterUsage.html"
    },
    "RegisterUsage": {
      "description": "Grants permission to to verify that the customer running your paid software is subscribed to your product on AWS Marketplace, enabling you to guard against unauthorized use. Meters software use per ECS task, per hour, with usage prorated to the second",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/marketplacemetering/latest/APIReference/API_RegisterUsage.html"
    },
    "ResolveCustomer": {
      "description": "Grants permission to resolve a registration token to obtain a CustomerIdentifier and product code",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/marketplacemetering/latest/APIReference/API_ResolveCustomer.html"
    }
  },
  "resourceTypes": {},
  "conditionKeys": {}
}

=== ZeePal/aws-iam-actions/data/resource-groups/aws_resource_groups.json
{
  "name": "AWS Resource Groups",
  "prefix": "resource-groups",
  "url": "https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsresourcegroups.html",
  "actions": {
    "CreateGroup": {
      "description": "Grants permission to create a resource group with a specified name, description, and resource query",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [
        "aws:RequestTag/${TagKey}",
        "aws:TagKeys"
      ],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/ARG/latest/APIReference/API_CreateGroup.html"
    },
    "DeleteGroup": {
      "description": "Grants permission to delete a specified resource group",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {
        "group": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/ARG/latest/APIReference/API_DeleteGroup.html"
    },
    "GetGroup": {
      "description": "Grants permission to get information of a specified resource group",
      "accessLevel": "Read",
      "permissionOnly": false,
      "resourceTypes": {
        "group": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/ARG/latest/APIReference/API_GetGroup.html"
    },
    "GetGroupConfiguration": {
      "description": "Grants permission to get the service configuration associated with the specified resource group",
      "accessLevel": "Read",
      "permissionOnly": false,
      "resourceTypes": {
        "group": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/ARG/latest/APIReference/API_GetGroupConfiguration.html"
    },
    "GetGroupQuery": {
      "description": "Grants permission to get the query associated with a specified resource group",
      "accessLevel": "Read",
      "permissionOnly": false,
      "resourceTypes": {
        "group": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/ARG/latest/APIReference/API_GetGroupQuery.html"
    },
    "GetTags": {
      "description": "Grants permission to get the tags associated with a specified resource group",
      "accessLevel": "Read",
      "permissionOnly": false,
      "resourceTypes": {
        "group": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/ARG/latest/APIReference/API_GetTags.html"
    },
    "GroupResources": {
      "description": "Grants permission to add the specified resources to the specified group",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {
        "group": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/ARG/latest/APIReference/API_GroupResources.html"
    },
    "ListGroupResources": {
      "description": "Grants permission to list the resources that are members of a specified resource group",
      "accessLevel": "List",
      "permissionOnly": false,
      "resourceTypes": {
        "group": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [
        "cloudformation:DescribeStacks",
        "cloudformation:ListStackResources",
        "tag:GetResources"
      ],
      "url": "https://docs.aws.amazon.com/ARG/latest/APIReference/API_ListGroupResources.html"
    },
    "ListGroups": {
      "description": "Grants permission to list all resource groups in your account",
      "accessLevel": "List",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/ARG/latest/APIReference/API_ListGroups.html"
    },
    "PutGroupConfiguration": {
      "description": "Grants permission to put the service configuration associated with the specified resource group",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {
        "group": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/ARG/latest/APIReference/API_PutGroupConfiguration.html"
    },
    "PutGroupPolicy": {
      "description": "Grants permission to add a resource-based policy for the specified group",
      "accessLevel": "Write",
      "permissionOnly": true,
      "resourceTypes": {
        "group": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/license-manager/latest/userguide/management-role.html#service-linked-role-permissions-management-role"
    },
    "SearchResources": {
      "description": "Grants permission to search for AWS resources matching the given query",
      "accessLevel": "List",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [
        "cloudformation:DescribeStacks",
        "cloudformation:ListStackResources",
        "tag:GetResources"
      ],
      "url": "https://docs.aws.amazon.com/ARG/latest/APIReference/API_SearchResources.html"
    },
    "Tag": {
      "description": "Grants permission to tag a specified resource group",
      "accessLevel": "Tagging",
      "permissionOnly": false,
      "resourceTypes": {
        "group": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [
        "aws:RequestTag/${TagKey}",
        "aws:TagKeys"
      ],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/ARG/latest/APIReference/API_Tag.html"
    },
    "UngroupResources": {
      "description": "Grants permission to remove the specified resources from the specified group",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {
        "group": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/ARG/latest/APIReference/API_UngroupResources.html"
    },
    "Untag": {
      "description": "Grants permission to remove tags associated with a specified resource group",
      "accessLevel": "Tagging",
      "permissionOnly": false,
      "resourceTypes": {
        "group": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [
        "aws:TagKeys"
      ],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/ARG/latest/APIReference/API_Untag.html"
    },
    "UpdateGroup": {
      "description": "Grants permission to update a specified resource group",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {
        "group": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/ARG/latest/APIReference/API_UpdateGroup.html"
    },
    "UpdateGroupQuery": {
      "description": "Grants permission to update the query associated with a specified resource group",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {
        "group": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/ARG/latest/APIReference/API_UpdateGroupQuery.html"
    }
  },
  "resourceTypes": {
    "group": {
      "arn": "arn:${Partition}:resource-groups:${Region}:${Account}:group/${GroupName}",
      "conditionKeys": [
        "aws:ResourceTag/${TagKey}"
      ],
      "url": "https://docs.aws.amazon.com/ARG/latest/userguide/resource-groups.html"
    }
  },
  "conditionKeys": {
    "aws:RequestTag/${TagKey}": {
      "description": "Filters access by the presence of tag key-value pairs in the request",
      "type": "String",
      "url": "https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-requesttag"
    },
    "aws:ResourceTag/${TagKey}": {
      "description": "Filters access by tag key-value pairs attached to the resource",
      "type": "String",
      "url": "https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-resourcetag"
    },
    "aws:TagKeys": {
      "description": "Filters access by the presence of tag keys in the request",
      "type": "ArrayOfString",
      "url": "https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-tagkeys"
    }
  }
}

=== ZeePal/aws-iam-actions/data/simspaceweaver/aws_simspace_weaver.json
{
  "name": "AWS SimSpace Weaver",
  "prefix": "simspaceweaver",
  "url": "https://docs.aws.amazon.com/service-authorization/latest/reference/list_awssimspaceweaver.html",
  "actions": {
    "DeleteApp": {
      "description": "Grants permission to delete an app",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {
        "Simulation": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/simspaceweaver/latest/APIReference/API_DeleteApp.html"
    },
    "DeleteSimulation": {
      "description": "Grants permission to delete a simulation",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {
        "Simulation": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/simspaceweaver/latest/APIReference/API_DeleteSimulation.html"
    },
    "DescribeApp": {
      "description": "Grants permission to describe an app",
      "accessLevel": "Read",
      "permissionOnly": false,
      "resourceTypes": {
        "Simulation": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/simspaceweaver/latest/APIReference/API_DescribeApp.html"
    },
    "DescribeSimulation": {
      "description": "Grants permission to describe a simulation",
      "accessLevel": "Read",
      "permissionOnly": false,
      "resourceTypes": {
        "Simulation": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/simspaceweaver/latest/APIReference/API_DescribeSimulation.html"
    },
    "ListApps": {
      "description": "Grants permission to list apps",
      "accessLevel": "Read",
      "permissionOnly": false,
      "resourceTypes": {
        "Simulation": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/simspaceweaver/latest/APIReference/API_ListApps.html"
    },
    "ListSimulations": {
      "description": "Grants permission to list simulations",
      "accessLevel": "List",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/simspaceweaver/latest/APIReference/API_ListSimulations.html"
    },
    "ListTagsForResource": {
      "description": "Grants permission to list the tags for a resource",
      "accessLevel": "Read",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/simspaceweaver/latest/APIReference/API_ListTagsForResource.html"
    },
    "StartApp": {
      "description": "Grants permission to start an app",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {
        "Simulation": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/simspaceweaver/latest/APIReference/API_StartApp.html"
    },
    "StartClock": {
      "description": "Grants permission to start a simulation clock",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {
        "Simulation": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/simspaceweaver/latest/APIReference/API_StartClock.html"
    },
    "StartSimulation": {
      "description": "Grants permission to start a simulation",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {},
      "conditionKeys": [
        "aws:RequestTag/${TagKey}",
        "aws:TagKeys"
      ],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/simspaceweaver/latest/APIReference/API_StartSimulation.html"
    },
    "StopApp": {
      "description": "Grants permission to stop an app",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {
        "Simulation": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/simspaceweaver/latest/APIReference/API_StopApp.html"
    },
    "StopClock": {
      "description": "Grants permission to stop a simulation clock",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {
        "Simulation": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/simspaceweaver/latest/APIReference/API_StopClock.html"
    },
    "StopSimulation": {
      "description": "Grants permission to stop a simulation",
      "accessLevel": "Write",
      "permissionOnly": false,
      "resourceTypes": {
        "Simulation": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/simspaceweaver/latest/APIReference/API_StopSimulation.html"
    },
    "TagResource": {
      "description": "Grants permission to tag a resource",
      "accessLevel": "Tagging",
      "permissionOnly": false,
      "resourceTypes": {
        "Simulation": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [
        "aws:RequestTag/${TagKey}",
        "aws:TagKeys"
      ],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/simspaceweaver/latest/APIReference/API_TagResource.html"
    },
    "UntagResource": {
      "description": "Grants permission to untag a resource",
      "accessLevel": "Tagging",
      "permissionOnly": false,
      "resourceTypes": {
        "Simulation": {
          "required": true,
          "conditionKeys": []
        }
      },
      "conditionKeys": [
        "aws:TagKeys"
      ],
      "dependentActions": [],
      "url": "https://docs.aws.amazon.com/simspaceweaver/latest/APIReference/API_UntagResource.html"
    }
  },
  "resourceTypes": {
    "Simulation": {
      "arn": "arn:${Partition}:simspaceweaver:${Region}:${Account}:simulation/${SimulationName}",
      "conditionKeys": [
        "aws:ResourceTag/${TagKey}"
      ],
      "url": "https://docs.aws.amazon.com/simspaceweaver/latest/userguide/working-with_configuring-simulation.html"
    }
  },
  "conditionKeys": {
    "aws:RequestTag/${TagKey}": {
      "description": "Filters access by tags that are passed in the request",
      "type": "String",
      "url": "https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-requesttag"
    },
    "aws:ResourceTag/${TagKey}": {
      "description": "Filters access by tags associated with the resource",
      "type": "String",
      "url": "https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-resourcetag"
    },
    "aws:TagKeys": {
      "description": "Filters access by tag keys that are passed in the request",
      "type": "ArrayOfString",
      "url": "https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-tagkeys"
    }
  }
}
